# Generated by Django 6.0.2 on 2026-02-10 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_reels', to=settings.AUTH_USER_MODEL),
        ),
    ]
