# Generated by Django 6.0.2 on 2026-02-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_comment_post_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
